const flights = [{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "easyjet",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "easyjet",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 150,
    "depart_price": 125,
    "depart_airline": "ryanair",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 160,
    "return_price": 140, 
    "return_airline": "ryanair",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 100,
    "depart_price": 200,
    "depart_airline": "ryanair",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 110,
    "return_price": 250, 
    "return_airline": "iberia",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 230,
    "depart_price": 100,
    "depart_airline": "britishairways",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 245,
    "return_price": 90, 
    "return_airline": "britishairways",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "easyjet",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "easyjet",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "iberia",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "ibera",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "norwegian",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "norwegian",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "easyjet",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "easyjet",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "aireuropa",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "easyjet",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "aireuropa",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "easyjet",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "norwegian",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "iberia",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "norwegian",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "easyjet",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "iberia",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "iberia",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "britishairways",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "britishairways",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "easyjet",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "britishairways",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "easyjet",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "britishairways",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "easyjet",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "iberia",
    "return_type": "Direct",
},{
    "depart_from_time": "17:25",
    "depart_to_time": "20:55",
    "depart_duration": 130,
    "depart_price": 120,
    "depart_airline": "iberia",
    "depart_type": "Direct",

    "return_from_time": "21:50",
    "return_to_time": "23:10",
    "return_duration": 140,
    "return_price": 120, 
    "return_airline": "iberia",
    "return_type": "Direct",
},
];

module.exports = {
    flights
}